name: invest_mobile
description: A new Flutter project.
publish_to: 'none'
version: 1.1.7+1

environment:
  sdk: '>=2.19.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  provider: ^6.0.2
  smooth_page_indicator: ^1.0.0+2
  flutter_svg: ^2.0.10+1
  dotted_line: ^3.1.0
  http: ^1.2.1
  flutter_spinkit: ^5.1.0
  flutter_native_splash: ^2.1.5
  lottie: ^3.1.2
  intl: ^0.19.0
  file_picker: ^8.0.3
  dio: ^5.0.2
  fl_chart: ^0.68.0
  badges: ^3.1.1
  image_cropper: ^6.0.0
  image_picker: ^1.1.2
  shared_preferences: ^2.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^4.0.0

flutter_icons:
  android: true
  ios: true
  image_path: "images/image/playstore.png"

flutter_native_splash:
  color: "#000000"
  image: images/image/log.png

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - images/svg/
    - images/image/

  fonts:
    - family: dmSans
      fonts:
        - asset: fonts/DMSans-Regular.ttf
        - asset: fonts/DMSans-Italic.ttf
          style: italic
        - asset: fonts/DMSans-Medium.ttf
          weight: 500
        - asset: fonts/DMSans-MediumItalic.ttf
          style: italic
          weight: 500
        - asset: fonts/DMSans-Bold.ttf
          weight: 700
        - asset: fonts/DMSans-BoldItalic.ttf
          style: italic
          weight: 700
